---
- hosts: DC1_SEs
  gather_facts: no
  become: yes
  tasks:  
    - name: Copy Secure channel cert to SE 
      copy:
        src: /path/to/cacert.pem
        dest: /bootstrap/cacert.pem
    - name: Fix secure channel common name
        content: "secure_channel_cert_common_name"
        dest: /bootstrap/cn.txt
    - name: stop se_supervisor process
        systemd:
    	state: stopped
    	name: se_supervisor.service
    - name: start se_supervisor process
        systemd:
        state: started
        name: se_supervisor.service
